name: CI/CD GITHUB
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_auth:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.2.0
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Create .env file
      run: |
        echo "MONGODB_AUTH_URI=mongodb://localhost:27017/auth_test" >> auth/.env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> auth/.env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> product/.env
        echo "MONGODB_PRODUCT_URI=mongodb://localhost:27017/product_test" >> product/.env
        echo "NODE_ENV=test" >> product/.env
        echo "LOGIN_TEST_USER=${{ secrets.LOGIN_TEST_USER }}" >> product/.env
        echo "LOGIN_TEST_PASSWORD=${{ secrets.LOGIN_TEST_PASSWORD }}" >> product/.env

    - name: Install dependencies
      run: |
        npm ci --prefix auth
        npm ci --prefix product
        npm ci
    - name: Start Auth service
      run: |
        cd auth && npm start &
        timeout 60 bash -c 'until curl -s http://localhost:3000/dashboard > /dev/null; do sleep 2; done'
    - name: Setup test user
      run: |
        echo "Creating test user..."
        curl -X POST http://localhost:3000/register \
        -H "Content-Type: application/json" \
        -d '{"username":"${{ secrets.LOGIN_TEST_USER }}","password":"${{ secrets.LOGIN_TEST_PASSWORD }}"}'
    - name: Run tests
      run: |
        npm test --prefix auth
        npm test --prefix product